// <auto-generated />
using System;
using CarRental.CarRental.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRental.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    [Migration("20251222180918_secound")]
    partial class secound
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Mileage")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PurchaseCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RentalAgentUserId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("RentalAgentUserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.RentalContract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExtraFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RentalAgentId")
                        .HasColumnType("int");

                    b.Property<int?>("RentalAgentUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ContractId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RentalAgentId");

                    b.HasIndex("RentalAgentUserId");

                    b.ToTable("RentalContracts");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Role").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.Admin", b =>
                {
                    b.HasBaseType("CarRental.CarRental.DAL.Entities.User");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            IsActive = true,
                            Password = "admin123",
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = 3,
                            IsActive = true,
                            Password = "Hmedat123",
                            UserName = "Hmedat"
                        });
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.RentalAgent", b =>
                {
                    b.HasBaseType("CarRental.CarRental.DAL.Entities.User");

                    b.HasDiscriminator().HasValue("Agent");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.Car", b =>
                {
                    b.HasOne("CarRental.CarRental.DAL.Entities.Supplier", "Supplier")
                        .WithMany("Cars")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.Customer", b =>
                {
                    b.HasOne("CarRental.CarRental.DAL.Entities.RentalAgent", null)
                        .WithMany("Customers")
                        .HasForeignKey("RentalAgentUserId");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.RentalContract", b =>
                {
                    b.HasOne("CarRental.CarRental.DAL.Entities.Car", "Car")
                        .WithMany("RentalContracts")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.CarRental.DAL.Entities.Customer", "Customer")
                        .WithMany("RentalContracts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.CarRental.DAL.Entities.RentalAgent", "RentalAgent")
                        .WithMany()
                        .HasForeignKey("RentalAgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRental.CarRental.DAL.Entities.RentalAgent", null)
                        .WithMany("RentalContracts")
                        .HasForeignKey("RentalAgentUserId");

                    b.Navigation("Car");

                    b.Navigation("Customer");

                    b.Navigation("RentalAgent");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.Car", b =>
                {
                    b.Navigation("RentalContracts");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.Customer", b =>
                {
                    b.Navigation("RentalContracts");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.Supplier", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarRental.CarRental.DAL.Entities.RentalAgent", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("RentalContracts");
                });
#pragma warning restore 612, 618
        }
    }
}
